spring:
  datasource:
    url: jdbc:aws-wrapper:postgresql://db-identifier.cluster-XYZ.us-east-2.rds.amazonaws.com:5432/postgres
    username: username
    password: password
    driver-class-name: software.amazon.jdbc.Driver
    hikari:
      data-source-properties:
        wrapperPlugins: failover,efm2
        wrapperDialect: aurora-pg
      max-lifetime: 840000
      minimum-idle: 20
      maximum-pool-size: 20
      idle-timeout: 900000
      read-only: true
