name: Run Aurora Integration Tests CodeBuild

on:
  workflow_dispatch:

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  aurora-integration-tests:
    strategy:
      matrix:
        engine_version: ["latest"]
        environment: ["mysql"]
    runs-on: codebuild-jdbcWrapper-${{ github.run_id }}-${{ github.run_attempt }}
    environment: ${{ matrix.environment }}_integ
    steps:
      - name: 'Clone repository'
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: 'Set up JDK 8'
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 8
      - name: 'Configure AWS credentials'
        id: creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ADMIN_ROLE }}
          role-session-name: run_integration_test_codebuild
          role-duration-seconds: 21600
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          output-credentials: true
      - name: Run integration tests
        run: |
          export GRADLE_OPTS="-Xmx6g -XX:MaxMetaspaceSize=1g"
          ./gradlew --no-parallel --no-daemon test-rds-proxy-${{ matrix.environment }}-aurora
        env:
          AURORA_CLUSTER_DOMAIN: ${{ secrets.DB_CONN_SUFFIX }}
          RDS_DB_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_ACCESS_KEY_ID: ${{ steps.creds.outputs.aws-access-key-id }}
          AWS_SECRET_ACCESS_KEY: ${{ steps.creds.outputs.aws-secret-access-key }}
          AWS_SESSION_TOKEN: ${{ steps.creds.outputs.aws-session-token }}
          IAM_ROLE_ARN: ${{ secrets.ADMIN_ROLE }}
          MYSQL_VERSION: "latest"
          PG_VERSION: "latest"
      - name: 'Archive junit results ${{ matrix.engine_version }}'
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-report-${{ matrix.engine_version }}
          path: ./wrapper/build/test-results
          retention-days: 5
      - name: 'Archive html summary report ${{ matrix.engine_version }}'
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: html-summary-report-${{ matrix.engine_version }}
          path: ./wrapper/build/report
          retention-days: 5
